export const ApiPaths = {
  BRANDS: "/brands",
  BANNERS: "/banners",
  CATEGORIES: "/categories",
  FAQS: "/faqs",
  BLOGS: "/blogs",
  USERS: "/users",
  HOME: "/home/products",
  ALL_PRODUCTS: "/all/products",
  WISHLIST: "/favorites/user",
  FAVORITES: "/favorites",
  CART: "/cart",
  CART_USER: "/cart/user",
  PRODUCTS: "/products",
  ADDRESSES: "/addresses",
  ADDRESSES_USER: "/addresses/user",
  ORDER_USER: "/order/user",
  CANCEL_ORDER: "/order/cancel",
  PLACE_ORDER: "/placeOrder",
  RATING: "/ratings",
  UPLOAD: "/upload",
};
// ABOUTFITNESS : "/aboutfitness",